export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE";

export const START_QUIZ = "START_QUIZ";
export const END_QUIZ = "END_QUIZ";

export const MARK_ANSWER = "MARK_ANSWER";